add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');
add_cus_dep('acn', 'acr', 0, 'run_makeglossaries');

sub run_makeglossaries {
  if ( -x "./custommakeglossaries" ) {
    system("./custommakeglossaries '$_[0]'");
    return
  }
  if ( $silent ) {
    system("makeglossaries -q '$_[0]'")
  }
  else {
    system("makeglossaries '$_[0]'")
  }
}
